# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iceberg}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christopher Durtschi"]
  s.date = %q{2010-12-27}
  s.description = %q{Forum as Rack middleware}
  s.email = %q{christopher.durtschi@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "iceberg.gemspec",
     "lib/helpers/utilities.rb",
     "lib/helpers/visuals.rb",
     "lib/iceberg.rb",
     "lib/mixins/external_layout.rb",
     "lib/mixins/filters.rb",
     "lib/mixins/stringex.rb",
     "lib/models/board.rb",
     "lib/models/post.rb",
     "lib/models/topic.rb",
     "lib/models/topic_view.rb",
     "lib/plugins/named_route_plugin.rb",
     "lib/plugins/named_route_plugin/named_route.rb",
     "lib/plugins/named_route_plugin/routing_helpers.rb",
     "lib/routes.rb",
     "lib/routes/boards.rb",
     "lib/routes/posts.rb",
     "lib/routes/topics.rb",
     "lib/views/boards/edit.haml",
     "lib/views/boards/index.haml",
     "lib/views/boards/new.haml",
     "lib/views/boards/show.builder",
     "lib/views/boards/show.haml",
     "lib/views/layout.haml",
     "lib/views/posts/edit.haml",
     "lib/views/posts/new.haml",
     "lib/views/topics/edit.haml",
     "lib/views/topics/move.haml",
     "lib/views/topics/new.haml",
     "lib/views/topics/show.builder",
     "lib/views/topics/show.haml",
     "ruby_version",
     "sinatra_more/.document",
     "sinatra_more/.gitignore",
     "sinatra_more/IDEAS.md",
     "sinatra_more/LICENSE",
     "sinatra_more/README.rdoc",
     "sinatra_more/ROADMAP",
     "sinatra_more/Rakefile",
     "sinatra_more/TODO",
     "sinatra_more/VERSION",
     "sinatra_more/bin/sinatra_gen",
     "sinatra_more/generators/base_app/.gitignore",
     "sinatra_more/generators/base_app/Gemfile",
     "sinatra_more/generators/base_app/app/.empty_directory",
     "sinatra_more/generators/base_app/app/helpers/.empty_directory",
     "sinatra_more/generators/base_app/app/helpers/view_helpers.rb",
     "sinatra_more/generators/base_app/app/mailers/.empty_directory",
     "sinatra_more/generators/base_app/app/models/.empty_directory",
     "sinatra_more/generators/base_app/app/routes/.empty_directory",
     "sinatra_more/generators/base_app/app/views/.empty_directory",
     "sinatra_more/generators/base_app/config.ru.tt",
     "sinatra_more/generators/base_app/config/boot.rb.tt",
     "sinatra_more/generators/base_app/config/dependencies.rb.tt",
     "sinatra_more/generators/base_app/lib/.empty_directory",
     "sinatra_more/generators/base_app/log/.empty_directory",
     "sinatra_more/generators/base_app/public/images/.empty_directory",
     "sinatra_more/generators/base_app/public/images/.gitignore",
     "sinatra_more/generators/base_app/public/javascripts/.empty_directory",
     "sinatra_more/generators/base_app/public/stylesheets/.empty_directory",
     "sinatra_more/generators/base_app/test/models/.empty_directory",
     "sinatra_more/generators/base_app/test/routes/.empty_directory",
     "sinatra_more/generators/base_app/test/test_config.rb.tt",
     "sinatra_more/generators/base_app/tmp/.empty_directory",
     "sinatra_more/generators/base_app/vendor/gems/.empty_directory",
     "sinatra_more/generators/components/component_actions.rb",
     "sinatra_more/generators/components/mocks/mocha_mock_gen.rb",
     "sinatra_more/generators/components/mocks/rr_mock_gen.rb",
     "sinatra_more/generators/components/orms/activerecord_orm_gen.rb",
     "sinatra_more/generators/components/orms/couchrest_orm_gen.rb",
     "sinatra_more/generators/components/orms/datamapper_orm_gen.rb",
     "sinatra_more/generators/components/orms/mongomapper_orm_gen.rb",
     "sinatra_more/generators/components/orms/sequel_orm_gen.rb",
     "sinatra_more/generators/components/renderers/erb_renderer_gen.rb",
     "sinatra_more/generators/components/renderers/haml_renderer_gen.rb",
     "sinatra_more/generators/components/scripts/jquery_script_gen.rb",
     "sinatra_more/generators/components/scripts/prototype_script_gen.rb",
     "sinatra_more/generators/components/scripts/rightjs_script_gen.rb",
     "sinatra_more/generators/components/tests/bacon_test_gen.rb",
     "sinatra_more/generators/components/tests/riot_test_gen.rb",
     "sinatra_more/generators/components/tests/rspec_test_gen.rb",
     "sinatra_more/generators/components/tests/shoulda_test_gen.rb",
     "sinatra_more/generators/components/tests/testspec_test_gen.rb",
     "sinatra_more/generators/generator_actions.rb",
     "sinatra_more/generators/skeleton_generator.rb",
     "sinatra_more/lib/sinatra_more.rb",
     "sinatra_more/lib/sinatra_more/mailer_plugin.rb",
     "sinatra_more/lib/sinatra_more/mailer_plugin/mail_object.rb",
     "sinatra_more/lib/sinatra_more/mailer_plugin/mailer_base.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/asset_tag_helpers.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/form_builder/abstract_form_builder.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/form_builder/standard_form_builder.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/form_helpers.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/format_helpers.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/output_helpers.rb",
     "sinatra_more/lib/sinatra_more/markup_plugin/tag_helpers.rb",
     "sinatra_more/lib/sinatra_more/render_plugin.rb",
     "sinatra_more/lib/sinatra_more/render_plugin/render_helpers.rb",
     "sinatra_more/lib/sinatra_more/routing_plugin.rb",
     "sinatra_more/lib/sinatra_more/routing_plugin/named_route.rb",
     "sinatra_more/lib/sinatra_more/routing_plugin/routing_helpers.rb",
     "sinatra_more/lib/sinatra_more/support_lite.rb",
     "sinatra_more/lib/sinatra_more/warden_plugin.rb",
     "sinatra_more/lib/sinatra_more/warden_plugin/warden_helpers.rb",
     "sinatra_more/sinatra_more.gemspec",
     "sinatra_more/test/active_support_helpers.rb",
     "sinatra_more/test/fixtures/mailer_app/app.rb",
     "sinatra_more/test/fixtures/mailer_app/views/demo_mailer/sample_mail.erb",
     "sinatra_more/test/fixtures/mailer_app/views/sample_mailer/anniversary_message.erb",
     "sinatra_more/test/fixtures/mailer_app/views/sample_mailer/birthday_message.erb",
     "sinatra_more/test/fixtures/markup_app/app.rb",
     "sinatra_more/test/fixtures/markup_app/views/capture_concat.erb",
     "sinatra_more/test/fixtures/markup_app/views/capture_concat.haml",
     "sinatra_more/test/fixtures/markup_app/views/content_for.erb",
     "sinatra_more/test/fixtures/markup_app/views/content_for.haml",
     "sinatra_more/test/fixtures/markup_app/views/content_tag.erb",
     "sinatra_more/test/fixtures/markup_app/views/content_tag.haml",
     "sinatra_more/test/fixtures/markup_app/views/fields_for.erb",
     "sinatra_more/test/fixtures/markup_app/views/fields_for.haml",
     "sinatra_more/test/fixtures/markup_app/views/form_for.erb",
     "sinatra_more/test/fixtures/markup_app/views/form_for.haml",
     "sinatra_more/test/fixtures/markup_app/views/form_tag.erb",
     "sinatra_more/test/fixtures/markup_app/views/form_tag.haml",
     "sinatra_more/test/fixtures/markup_app/views/link_to.erb",
     "sinatra_more/test/fixtures/markup_app/views/link_to.haml",
     "sinatra_more/test/fixtures/markup_app/views/mail_to.erb",
     "sinatra_more/test/fixtures/markup_app/views/mail_to.haml",
     "sinatra_more/test/fixtures/markup_app/views/meta_tag.erb",
     "sinatra_more/test/fixtures/markup_app/views/meta_tag.haml",
     "sinatra_more/test/fixtures/render_app/app.rb",
     "sinatra_more/test/fixtures/render_app/views/erb/test.erb",
     "sinatra_more/test/fixtures/render_app/views/haml/test.haml",
     "sinatra_more/test/fixtures/render_app/views/template/_user.haml",
     "sinatra_more/test/fixtures/render_app/views/template/haml_template.haml",
     "sinatra_more/test/fixtures/render_app/views/template/some_template.haml",
     "sinatra_more/test/fixtures/routing_app/app.rb",
     "sinatra_more/test/fixtures/routing_app/views/index.haml",
     "sinatra_more/test/fixtures/warden_app/app.rb",
     "sinatra_more/test/fixtures/warden_app/views/dashboard.haml",
     "sinatra_more/test/generators/test_skeleton_generator.rb",
     "sinatra_more/test/helper.rb",
     "sinatra_more/test/mailer_plugin/test_mail_object.rb",
     "sinatra_more/test/mailer_plugin/test_mailer_base.rb",
     "sinatra_more/test/markup_plugin/test_asset_tag_helpers.rb",
     "sinatra_more/test/markup_plugin/test_form_builder.rb",
     "sinatra_more/test/markup_plugin/test_form_helpers.rb",
     "sinatra_more/test/markup_plugin/test_format_helpers.rb",
     "sinatra_more/test/markup_plugin/test_output_helpers.rb",
     "sinatra_more/test/markup_plugin/test_tag_helpers.rb",
     "sinatra_more/test/test_mailer_plugin.rb",
     "sinatra_more/test/test_render_plugin.rb",
     "sinatra_more/test/test_routing_plugin.rb",
     "sinatra_more/test/test_warden_plugin.rb",
     "sinatra_more/vendor/pony/lib/pony.rb",
     "sinatra_more/vendor/pony/spec/base.rb",
     "sinatra_more/vendor/pony/spec/pony_spec.rb",
     "spec/helpers/visuals_spec.rb",
     "spec/iceberg_spec.rb",
     "spec/models/board_spec.rb",
     "spec/models/post_spec.rb",
     "spec/models/topic_spec.rb",
     "spec/routes/boards_spec.rb",
     "spec/routes/posts_spec.rb",
     "spec/routes/topics_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/app.rb",
     "spec/support/be_valid_asset.rb",
     "spec/support/custom_matchers.rb",
     "spec/support/fixtures.rb"
  ]
  s.homepage = %q{http://github.com/robotapocalypse/iceberg}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Forum as Rack middleware}
  s.test_files = [
    "spec/helpers/visuals_spec.rb",
     "spec/iceberg_spec.rb",
     "spec/models/board_spec.rb",
     "spec/models/post_spec.rb",
     "spec/models/topic_spec.rb",
     "spec/routes/boards_spec.rb",
     "spec/routes/posts_spec.rb",
     "spec/routes/topics_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app.rb",
     "spec/support/be_valid_asset.rb",
     "spec/support/custom_matchers.rb",
     "spec/support/fixtures.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<rack-flash>, ["= 0.1.1"])
      s.add_runtime_dependency(%q<sinatra>, ["= 0.9.4"])
      s.add_runtime_dependency(%q<dm-core>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-types>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-serializer>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-timestamps>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-validations>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-tags>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-is-list>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<dm-is-tree>, ["= 0.10.2"])
      s.add_runtime_dependency(%q<data_objects>, ["= 0.10.1"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<be_valid_asset>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<rack-flash>, ["= 0.1.1"])
      s.add_dependency(%q<sinatra>, ["= 0.9.4"])
      s.add_dependency(%q<dm-core>, ["= 0.10.2"])
      s.add_dependency(%q<dm-types>, ["= 0.10.2"])
      s.add_dependency(%q<dm-serializer>, ["= 0.10.2"])
      s.add_dependency(%q<dm-aggregates>, ["= 0.10.2"])
      s.add_dependency(%q<dm-timestamps>, ["= 0.10.2"])
      s.add_dependency(%q<dm-validations>, ["= 0.10.2"])
      s.add_dependency(%q<dm-tags>, ["= 0.10.2"])
      s.add_dependency(%q<dm-is-list>, ["= 0.10.2"])
      s.add_dependency(%q<dm-is-tree>, ["= 0.10.2"])
      s.add_dependency(%q<data_objects>, ["= 0.10.1"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["= 2.3.5"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<be_valid_asset>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<rack-flash>, ["= 0.1.1"])
    s.add_dependency(%q<sinatra>, ["= 0.9.4"])
    s.add_dependency(%q<dm-core>, ["= 0.10.2"])
    s.add_dependency(%q<dm-types>, ["= 0.10.2"])
    s.add_dependency(%q<dm-serializer>, ["= 0.10.2"])
    s.add_dependency(%q<dm-aggregates>, ["= 0.10.2"])
    s.add_dependency(%q<dm-timestamps>, ["= 0.10.2"])
    s.add_dependency(%q<dm-validations>, ["= 0.10.2"])
    s.add_dependency(%q<dm-tags>, ["= 0.10.2"])
    s.add_dependency(%q<dm-is-list>, ["= 0.10.2"])
    s.add_dependency(%q<dm-is-tree>, ["= 0.10.2"])
    s.add_dependency(%q<data_objects>, ["= 0.10.1"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["= 2.3.5"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<be_valid_asset>, [">= 0"])
  end
end

